package negrar.piberlo.antibiotichelper.model

object AntibioticiRepository {
    val antibiotici = listOf(
        Antibiotico(
            nome = "Amikacina",
            dosaggioRegolare = "15-20 mg/kg/die EV in 1-2 somministrazioni",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr > 60 ml/min: dose standard\n• ClCr 30-60 ml/min: 10 mg/kg/die\n• ClCr < 30 ml/min: 7,5 mg/kg/die\n• Emodialisi: dose secondo livelli plasmatici",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30-60 minuti",
            dosaggiParticolari = "In infezioni gravi o da Pseudomonas, preferire la dose più alta. Monitorare livelli plasmatici.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Amikacina)"),
            volumeInfusione = "100-200 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Amoxicillina/Clavulanato",
            dosaggioRegolare = "1g/200mg ogni 8 ore EV. Nelle infezioni più gravi o nel sospetto di anaerobi 2g ogni 8 ore",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "• ClCr > 30 ml/min: dose standard (1g/200mg ogni 8 ore)\n• ClCr 10-30 ml/min: 1g/200mg ogni 12 ore\n• ClCr < 10 ml/min: 1g/200mg ogni 24 ore\n• Emodialisi: 1g/200mg ogni 24 ore, aggiungere 500mg/125mg dopo ogni seduta di dialisi",
            adattamentiEpatici = "Usare con cautela in caso di insufficienza epatica grave; monitorare la funzionalità epatica durante il trattamento",
            tempoInfusione = "30-60 minuti",
            dosaggioOrale = "875/125mg ogni 8-12 ore",
            formulazioneOrale = "Compresse, sospensione",
            dosaggiParticolari = "In infezioni gravi (es. sospetto di anaerobi, polmoniti severe, infezioni intra-addominali) può essere usata la dose di 2g/200mg ogni 8 ore EV.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Amoxicillina+Clavulanato)"),
            volumeInfusione = "50-100 ml (minimo 50 ml)"
        ),
        Antibiotico(
            nome = "Ampicillina",
            dosaggioRegolare = "1-2g ogni 4-6 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "• ClCr > 30 ml/min: dose standard\n• ClCr 10-30 ml/min: 1-2g ogni 8 ore\n• ClCr < 10 ml/min: 1-2g ogni 12 ore\n• Emodialisi: 1-2g ogni 12 ore",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "15-30 minuti",
            dosaggiParticolari = "Meningite: 2g ogni 4 ore EV. Endocardite enterococcica: 2g ogni 4 ore EV.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Ampicillina)"),
            volumeInfusione = "50-100 ml (minimo 50 ml)"
        ),
        Antibiotico(
            nome = "Anidulafungina",
            dosaggioRegolare = "Dose di carico 200mg EV, poi 100mg ogni 24 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "90 minuti",
            dosaggiParticolari = "Candidemia e candidiasi invasiva.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Anidulafungina)"),
            volumeInfusione = "250 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Azitromicina",
            dosaggioRegolare = "500mg ogni 24 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Usare con cautela in insufficienza epatica grave",
            tempoInfusione = "60 minuti",
            dosaggioOrale = "500mg ogni 24 ore",
            formulazioneOrale = "Compresse, sospensione",
            dosaggiParticolari = "Polmonite atipica, infezioni da clamidia.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Azitromicina)"),
            volumeInfusione = "250 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Caspofungina",
            dosaggioRegolare = "Dose di carico 70mg EV, poi 50mg ogni 24 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Ridurre a 35mg/die in insufficienza epatica moderata-grave",
            tempoInfusione = "60 minuti",
            dosaggiParticolari = "Candidemia, candidiasi invasiva, aspergillosi refrattaria.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Caspofungina)"),
            volumeInfusione = "250 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Cefazolina",
            dosaggioRegolare = "1-2g ogni 8 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr > 55 ml/min: dose standard\n• ClCr 35-54 ml/min: 1g ogni 12 ore\n• ClCr < 35 ml/min: 1g ogni 24 ore\n• Emodialisi: 1g dopo ogni dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30 minuti",
            dosaggiParticolari = "Profilassi chirurgica: 2g EV 30-60 minuti prima dell'incisione.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Cefazolina)"),
            volumeInfusione = "50-100 ml (minimo 50 ml)"
        ),
        Antibiotico(
            nome = "Cefepime",
            dosaggioRegolare = "2g ogni 8-12 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "• ClCr > 60 ml/min: 2g ogni 8-12 ore\n• ClCr 30-60 ml/min: 2g ogni 12-24 ore\n• ClCr 11-29 ml/min: 1g ogni 12-24 ore\n• ClCr ≤ 10 ml/min: 0,5g ogni 24 ore\n• Emodialisi: 1g dopo ogni dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30 minuti",
            dosaggiParticolari = "Meningite: 2g ogni 8 ore EV.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Cefepime)"),
            volumeInfusione = "100 ml (minimo 50 ml)"
        ),
        Antibiotico(
            nome = "Cefiderocol",
            dosaggioRegolare = "2g ogni 8 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr > 60 ml/min: dose standard\n• ClCr 30-59 ml/min: 1,5g ogni 8 ore\n• ClCr 15-29 ml/min: 1g ogni 8 ore\n• ClCr < 15 ml/min: 0,75g ogni 12 ore\n• Emodialisi: 0,75g ogni 12 ore dopo dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "180 minuti",
            dosaggiParticolari = "Infezioni da Gram-negativi multiresistenti, inclusi carbapenemasi produttori.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Cefiderocol)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Ceftarolina",
            dosaggioRegolare = "600mg ogni 12 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr > 50 ml/min: dose standard\n• ClCr 30-50 ml/min: 400mg ogni 12 ore\n• ClCr 15-30 ml/min: 300mg ogni 12 ore\n• ClCr < 15 ml/min: 200mg ogni 12 ore",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "60 minuti",
            dosaggiParticolari = "Polmoniti gravi, infezioni complicate della cute e dei tessuti molli.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Ceftarolina)"),
            volumeInfusione = "250 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Ceftazidima",
            dosaggioRegolare = "1-2g ogni 8-12 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "• ClCr > 50 ml/min: dose standard (1-2g ogni 8-12 ore)\n• ClCr 30-50 ml/min: 1g ogni 12 ore\n• ClCr < 30 ml/min: 0,5-1g ogni 24 ore\n• Emodialisi: 1g dopo ogni dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30-60 minuti",
            dosaggiParticolari = "Meningite: 2g ogni 8 ore EV. Infezioni gravi da Pseudomonas.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Ceftazidima)"),
            volumeInfusione = "100 ml (minimo 50 ml)"
        ),
        Antibiotico(
            nome = "Ceftazidima/Avibactam",
            dosaggioRegolare = "2g/0,5g ogni 8 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr > 50 ml/min: dose standard\n• ClCr 31-50 ml/min: 1g/0,25g ogni 8 ore\n• ClCr 16-30 ml/min: 0,75g/0,188g ogni 12 ore\n• ClCr ≤ 15 ml/min: 0,75g/0,188g ogni 24 ore\n• Emodialisi: 0,75g/0,188g ogni 24 ore dopo dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "120 minuti",
            dosaggiParticolari = "Infezioni complicate da Gram-negativi resistenti, KPC, OXA-48.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Ceftazidima+Avibactam)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Ceftriaxone",
            dosaggioRegolare = "Adulto: 2g ogni 24 ore EV (fino a 4g/die in infezioni gravi)",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "Non sono necessari aggiustamenti per insufficienza renale, tranne in caso di insufficienza renale grave associata a insufficienza epatica grave",
            adattamentiEpatici = "Usare con cautela in caso di insufficienza epatica grave",
            tempoInfusione = "30 minuti",
            dosaggiParticolari = "• Meningite: 2g ogni 12 ore EV.\n• Gonorrea: dose singola 1g EV/IM.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Ceftriaxone)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Ciprofloxacina",
            dosaggioRegolare = "400mg ogni 8-12 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "• ClCr 30-50 ml/min: 200-400mg ogni 12 ore\n• ClCr < 30 ml/min: 200-400mg ogni 24 ore",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "60 minuti",
            dosaggioOrale = "500-750mg ogni 12 ore",
            formulazioneOrale = "Compresse",
            dosaggiParticolari = "Infezioni urinarie complicate, infezioni da Pseudomonas.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Ciprofloxacina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Claritromicina",
            dosaggioRegolare = "Adulto: 500-750mg ogni 24 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "• ClCr > 50 ml/min: dose standard (500-750mg ogni 24 ore)\n• ClCr 20-49 ml/min: 500mg iniziale, poi 250mg ogni 24 ore\n• ClCr < 20 ml/min: 500mg iniziale, poi 250mg ogni 48 ore\n• Emodialisi: 500mg iniziale, poi 250mg ogni 48 ore",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "60 minuti",
            dosaggiParticolari = "Polmonite nosocomiale: 750mg ogni 24 ore EV.",
            dosaggioOrale = "500-750mg ogni 24 ore",
            formulazioneOrale = "Compresse",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Claritromicina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Clindamicina",
            dosaggioRegolare = "Adulto: 600-900mg ogni 8 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Usare con cautela in insufficienza epatica grave",
            tempoInfusione = "30-60 minuti",
            dosaggiParticolari = "Infezioni da anaerobi, infezioni cutanee e ossee.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Clindamicina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Colistina",
            dosaggioRegolare = "2-3 milioni UI ogni 8 ore EV (dose in UI, non mg!)",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr 50-80 ml/min: 2 milioni UI ogni 12 ore\n• ClCr < 50 ml/min: 1-2 milioni UI ogni 12-24 ore",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30-60 minuti",
            dosaggiParticolari = "Infezioni da Gram-negativi multiresistenti. Attenzione a monitoraggio renale e neurologico.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Colistina)"),
            volumeInfusione = "50-100 ml (minimo 50 ml)"
        ),
        Antibiotico(
            nome = "Daptomicina",
            dosaggioRegolare = "Adulto: 4-6 mg/kg ogni 24 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr < 30 ml/min: ogni 48 ore",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30 minuti",
            dosaggiParticolari = "Batteriemie, endocarditi da Stafilococco resistente. Non usare in polmoniti.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Daptomicina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Doxiciclina",
            dosaggioRegolare = "100mg ogni 12 ore EV o per os",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Usare con cautela in insufficienza epatica grave",
            tempoInfusione = "60 minuti",
            dosaggioOrale = "100mg ogni 12 ore",
            formulazioneOrale = "Compresse, capsules",
            dosaggiParticolari = "Malattia di Lyme, infezioni da rickettsie, polmoniti atipiche.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Doxiciclina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Ertapenem",
            dosaggioRegolare = "Adulto: 1g ogni 24 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "• ClCr > 30 ml/min: dose standard (1g ogni 24 ore)\n• ClCr ≤ 30 ml/min: 500mg ogni 24 ore\n• Emodialisi: 500mg ogni 24 ore, somministrare dopo dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30 minuti",
            dosaggiParticolari = "Non raccomandato per infezioni da Pseudomonas o Acinetobacter.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Ertapenem)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Fluconazolo",
            dosaggioRegolare = "Adulto: 400mg dose di carico, poi 200-400mg ogni 24 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "• ClCr < 50 ml/min: dimezzare la dose",
            adattamentiEpatici = "Usare con cautela in insufficienza epatica grave",
            tempoInfusione = "30-60 minuti",
            dosaggiParticolari = "Candidemie, meningite criptococcica.",
            dosaggioOrale = "200-400mg ogni 24 ore",
            formulazioneOrale = "Compresse, sospensione",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Fluconazolo)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Fosfomicina",
            dosaggioRegolare = "4-8g ogni 6-8 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr < 40 ml/min: 4g ogni 12 ore\n• Emodialisi: 4g dopo dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "60 minuti",
            dosaggioOrale = "3g dose singola",
            formulazioneOrale = "Bustine",
            dosaggiParticolari = "Infezioni urinarie complicate, infezioni da batteri multiresistenti.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Fosfomicina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Gentamicina",
            dosaggioRegolare = "Adulto: 5-7 mg/kg/die EV in unica somministrazione (o 1,5-2 mg/kg ogni 8 ore)",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr > 60 ml/min: dose standard\n• ClCr 30-60 ml/min: 3 mg/kg/die\n• ClCr < 30 ml/min: 2 mg/kg/die\n• Emodialisi: dose secondo livelli plasmatici",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30-60 minuti",
            dosaggiParticolari = "Endocardite: 3 mg/kg/die in 2-3 somministrazioni. Monitorare livelli plasmatici.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Gentamicina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Imipenem",
            dosaggioRegolare = "Adulto: 500mg-1g ogni 6-8 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr > 70 ml/min: dose standard (500mg-1g ogni 6-8 ore)\n• ClCr 41-70 ml/min: 500mg ogni 6 ore\n• ClCr 21-40 ml/min: 250-500mg ogni 6-8 ore\n• ClCr 6-20 ml/min: 250mg ogni 8-12 ore\n• ClCr ≤ 5 ml/min: controindicato\n• Emodialisi: 250-500mg ogni 12 ore dopo dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "20-30 minuti",
            dosaggiParticolari = "Meningite: 1g ogni 6 ore EV.",
            note = "Rischio di slatentizzazione di crisi epilettiche.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Imipenem)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Isavuconazolo",
            dosaggioRegolare = "Adulto: dose di carico 200mg ogni 8 ore per 6 dosi, poi 200mg ogni 24 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Usare con cautela in insufficienza epatica grave",
            tempoInfusione = "60 minuti",
            dosaggiParticolari = "Aspergillosi invasiva, mucormicosi.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Isavuconazolo)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Levofloxacina",
            dosaggioRegolare = "Adulto: 500-750mg ogni 24 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "• ClCr > 50 ml/min: dose standard (500-750mg ogni 24 ore)\n• ClCr 20-49 ml/min: 500mg iniziale, poi 250mg ogni 24 ore\n• ClCr < 20 ml/min: 500mg iniziale, poi 250mg ogni 48 ore\n• Emodialisi: 500mg iniziale, poi 250mg ogni 48 ore",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "60 minuti",
            dosaggiParticolari = "Polmonite nosocomiale: 750mg ogni 24 ore EV.",
            dosaggioOrale = "500-750mg ogni 24 ore",
            formulazioneOrale = "Compresse",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Levofloxacina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Linezolid",
            dosaggioRegolare = "Adulto: 600mg ogni 12 ore EV",
            soluzioniDiluizione = "Soluzione precostituita 300ml",
            formulazioneOrale = "Compresse, non frantumabili",
            dosaggioOrale = "600mg (1 cp) ogni 12 ore",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30-120 minuti",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Linezolid)"),
            note = "- Monitorare emocromo per rischio mielotossicità.\n" +
                    "- Verificata ✅"
        ),
        Antibiotico(
            nome = "Meropenem",
            dosaggioRegolare = "1g ogni 8 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr > 50 ml/min: 1g ogni 8 ore\n• ClCr 26-50 ml/min: 1g ogni 12 ore\n• ClCr 10-25 ml/min: 0,5g ogni 12 ore\n• ClCr < 10 ml/min: 0,5g ogni 24 ore\n• Emodialisi: 0,5g ogni 24 ore, aggiungere 0,25g dopo ogni dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "15-30 minuti (ideale: 3 ore in infusione prolungata)",
            dosaggiParticolari = "In caso di meningite o polmonite in fibrosi cistica, la dose raccomandata è 2g ogni 8 ore EV.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Meropenem)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Meropenem/Vaborbactam",
            dosaggioRegolare = "2g/2g ogni 8 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr > 50 ml/min: dose standard\n• ClCr 30-49 ml/min: 1g/1g ogni 8 ore\n• ClCr 15-29 ml/min: 1g/1g ogni 12 ore\n• ClCr < 15 ml/min: non raccomandato",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "180 minuti",
            dosaggiParticolari = "Infezioni complicate da Enterobacteriaceae resistenti (KPC).",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Meropenem+Vaborbactam)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Metronidazolo",
            dosaggioRegolare = "Adulto: 500mg ogni 8-12 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Ridurre la dose in caso di grave insufficienza epatica",
            tempoInfusione = "30-60 minuti",
            dosaggiParticolari = "Colite da Clostridioides difficile: 500mg ogni 8 ore per via orale.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Metronidazolo)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Micafungina",
            dosaggioRegolare = "100mg ogni 24 ore EV (fino a 200mg in infezioni invasive)",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "60 minuti",
            dosaggiParticolari = "Candidemia, profilassi in pazienti ematologici.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Micafungina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Oxacillina",
            dosaggioRegolare = "Adulto: 2g ogni 4-6 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Usare con cautela in insufficienza epatica grave",
            tempoInfusione = "60 minuti",
            dosaggiParticolari = "Endocardite da Stafilococco sensibile: 2g ogni 4 ore EV.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Oxacillina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Piperacillina/Tazobactam",
            dosaggioRegolare = "Adulto: 4g/0,5g ogni 8 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr > 40 ml/min: dose standard (4g/0,5g ogni 8 ore)\n• ClCr 20-40 ml/min: 4g/0,5g ogni 12 ore\n• ClCr < 20 ml/min: 2g/0,25g ogni 12 ore\n• Emodialisi: 2g/0,25g ogni 8 ore durante i giorni senza dialisi; aggiungere 0,75g/0,094g dopo ogni seduta di dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti significativi",
            tempoInfusione = "30 minuti (ideale: 3-4 ore in infusione prolungata)",
            dosaggiParticolari = "In caso di infezioni da Pseudomonas o in pazienti critici, può essere considerata l'infusione prolungata (4g/0,5g in 3-4 ore ogni 8 ore).",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Piperacillina+Tazobactam)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Polimixina B",
            dosaggioRegolare = "1,5-2,5 mg/kg/die EV in 2 dosi",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "Non sono necessari aggiustamenti (ma monitorare funzione renale)",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "60 minuti",
            dosaggiParticolari = "Infezioni da Gram-negativi multiresistenti. Monitorare funzione renale e neurologica.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Polimixina+B)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Posaconazolo",
            dosaggioRegolare = "300mg ogni 24 ore EV (dopo dose di carico 300mg ogni 12 ore per 2 dosi)",
            soluzioniDiluizione = "Soluzione glucosata 5%",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Usare con cautela in insufficienza epatica grave",
            tempoInfusione = "90 minuti",
            dosaggioOrale = "300mg ogni 24 ore",
            formulazioneOrale = "Compresse, sospensione",
            dosaggiParticolari = "Profilassi e trattamento di infezioni fungine invasive (aspergillosi, mucormicosi).",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Posaconazolo)"),
            volumeInfusione = "250 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Rifampicina",
            dosaggioRegolare = "600mg ogni 24 ore EV o per os",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Ridurre la dose in caso di insufficienza epatica grave",
            tempoInfusione = "30 minuti",
            dosaggioOrale = "600mg ogni 24 ore",
            formulazioneOrale = "Compresse, capsule",
            dosaggiParticolari = "Tubercolosi, infezioni protesiche, sempre in associazione ad altri antibiotici.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Rifampicina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Teicoplanina",
            dosaggioRegolare = "400mg ogni 12 ore per 3 dosi (carico), poi 400mg ogni 24 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr < 60 ml/min: 200-400mg ogni 48 ore",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30-60 minuti",
            dosaggiParticolari = "Endocarditi, infezioni da MRSA, osteomieliti. Monitorare livelli plasmatici.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Teicoplanina)"),
            volumeInfusione = "100 ml (minimo 50 ml)"
        ),
        Antibiotico(
            nome = "Tigeciclina",
            dosaggioRegolare = "100mg dose di carico, poi 50mg ogni 12 ore EV",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "Non sono necessari aggiustamenti",
            adattamentiEpatici = "Usare con cautela in insufficienza epatica grave",
            tempoInfusione = "30-60 minuti",
            dosaggiParticolari = "Infezioni complicate addominali, cutanee, polmoniti. Non attiva su Pseudomonas.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Tigeciclina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Tobramicina",
            dosaggioRegolare = "5-7 mg/kg/die EV in unica somministrazione",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%)",
            adattamentiRenali = "• ClCr 30-60 ml/min: 3 mg/kg/die\n• ClCr < 30 ml/min: 2 mg/kg/die\n• Emodialisi: dose secondo livelli plasmatici",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "30-60 minuti",
            dosaggiParticolari = "Infezioni gravi da Gram-negativi, Pseudomonas. Monitorare livelli plasmatici.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Tobramicina)"),
            volumeInfusione = "100-200 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Trimetoprim/Sulfametossazolo",
            dosaggioRegolare = "Adulto: 160/800mg (1 cpr) ogni 12 ore per os o 5-10mg/kg/die (trimetoprim) EV in 2-4 dosi",
            soluzioniDiluizione = "Soluzione glucosata 5%",
            adattamentiRenali = "• ClCr 15-30 ml/min: metà dose\n• ClCr < 15 ml/min: evitare se possibile",
            adattamentiEpatici = "Usare con cautela in insufficienza epatica grave",
            tempoInfusione = "60-90 minuti",
            dosaggiParticolari = "Pneumocistosi: 15-20mg/kg/die (trimetoprim) EV in 3-4 dosi.",
            dosaggioOrale = "160/800mg ogni 12 ore",
            formulazioneOrale = "Compresse",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Trimetoprim+Sulfametossazolo)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Vancomicina",
            dosaggioRegolare = "Adulto: 15-20 mg/kg ogni 8-12 ore EV (dose iniziale tipica 1g ogni 12 ore)",
            soluzioniDiluizione = "Soluzione fisiologica (NaCl 0,9%) o glucosata 5%",
            adattamentiRenali = "• ClCr > 50 ml/min: dose standard\n• ClCr 20-49 ml/min: 15-20 mg/kg ogni 24 ore\n• ClCr < 20 ml/min: dose secondo livelli plasmatici\n• Emodialisi: dose secondo livelli plasmatici, spesso 500 mg dopo ogni dialisi",
            adattamentiEpatici = "Non sono necessari aggiustamenti",
            tempoInfusione = "Almeno 60 minuti per 1g (max 10 mg/min)",
            dosaggiParticolari = "Endocardite, osteomielite, meningite: target livelli plasmatici più elevati (15-20 mg/L).",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Vancomicina)"),
            volumeInfusione = "100 ml (minimo 100 ml)"
        ),
        Antibiotico(
            nome = "Voriconazolo",
            dosaggioRegolare = "6mg/kg ogni 12 ore (2 dosi), poi 4mg/kg ogni 12 ore EV",
            soluzioniDiluizione = "Soluzione glucosata 5%",
            adattamentiRenali = "Non sono necessari aggiustamenti (ma evitare EV se ClCr < 50 ml/min)",
            adattamentiEpatici = "Ridurre la dose in caso di insufficienza epatica moderata-grave",
            tempoInfusione = "120 minuti",
            dosaggioOrale = "200mg ogni 12 ore",
            formulazioneOrale = "Compresse, sospensione",
            dosaggiParticolari = "Aspergillosi invasiva, infezioni fungine resistenti.",
            linkUtili = listOf("[Cerca RCP su Google](https://www.google.com/search?q=RCP+Voriconazolo)"),
            volumeInfusione = "100-200 ml (minimo 100 ml)"
        )
    )
} 